#!/bin/bash
/opt/home/merit/inject.py abercrombie-us	 600 2>&1 >/var/log/inject/abercrombie_us.log &
/opt/home/merit/inject.py americaneagle-us	 600 2>&1 >/var/log/inject/americaneagle_us.log &
/opt/home/merit/inject.py anntaylor-us		 600 2>&1 >/var/log/inject/anntaylor_us.log &
/opt/home/merit/inject.py anthropologie-us	 600 2>&1 >/var/log/inject/anthropologie_us.log &
/opt/home/merit/inject.py asda_george-uk	 600 2>&1 >/var/log/inject/asda_george_uk.log &
/opt/home/merit/inject.py asos-uk		 600 2>&1 >/var/log/inject/asos_uk.log &
/opt/home/merit/inject.py asos-us		 600 2>&1 >/var/log/inject/asos_us.log &
/opt/home/merit/inject.py bananarepublic-us	 600 2>&1 >/var/log/inject/bananarepublic_us.log &
#/opt/home/merit/inject.py bealls-us		 600 2>&1 >/var/log/inject/bealls_us.log &
/opt/home/merit/inject.py bhs-uk		 600 2>&1 >/var/log/inject/bhs_uk.log &
/opt/home/merit/inject.py bloomingdales-us	 600 2>&1 >/var/log/inject/bloomingdales_us.log &
# /opt/home/merit/inject.py boohoo-uk	 600 2>&1 >/var/log/inject/boohoo_us.log &
/opt/home/merit/inject.py chicos-us		 600 2>&1 >/var/log/inject/chicos_us.log &
/opt/home/merit/inject.py coaststores-uk	  600 2>&1 >/var/log/inject/coaststores_uk.log &
/opt/home/merit/inject.py debenhams-uk		 600 2>&1 >/var/log/inject/debenhams_uk.log &
#/opt/home/merit/inject.py dorothy_perkins-uk	 600 2>&1 >/var/log/inject/dorothy_perkins_uk.log &
/opt/home/merit/inject.py evans-uk		 600 2>&1 >/var/log/inject/evans_uk.log &
#/opt/home/merit/inject.py express-us		 600 2>&1 >/var/log/inject/express_us.log &
/opt/home/merit/inject.py forever21-us		 600 2>&1 >/var/log/inject/forever21_us.log &
#/opt/home/merit/inject.py gap-uk		 600 2>&1 >/var/log/inject/gap_uk.log &
#/opt/home/merit/inject.py gap-us		 600 2>&1 >/var/log/inject/gap_us.log &
/opt/home/merit/inject.py h\&m-uk		 600 2>&1 >/var/log/inject/h\&m_uk.log &
# /opt/home/merit/inject.py harrods-uk		 600 2>&1 >/var/log/inject/harrods_uk.log &
#/opt/home/merit/inject.py hollister-us		 600 2>&1 >/var/log/inject/hollister-us.log &
/opt/home/merit/inject.py houseoffraser-uk	 600 2>&1 >/var/log/inject/houseoffraser_uk.log &
/opt/home/merit/inject.py jcpenney-us		 600 2>&1 >/var/log/inject/jcpenney_us.log &
/opt/home/merit/inject.py jcrew-us		 600 2>&1 >/var/log/inject/jcrew_us.log &
/opt/home/merit/inject.py jigsaw-uk		 600 2>&1 >/var/log/inject/jigsaw_uk.log &
/opt/home/merit/inject.py johnlewis-uk		 600 2>&1 >/var/log/inject/johnlewis_uk.log &
/opt/home/merit/inject.py kmart-us		 600 2>&1 >/var/log/inject/kmart_us.log &
#/opt/home/merit/inject.py kohls-us		 600 2>&1 >/var/log/inject/kohls_us.log &
/opt/home/merit/inject.py landsend-us		 600 2>&1 >/var/log/inject/landsend_us.log &
#/opt/home/merit/inject.py littlewoods-uk	 600 2>&1 >/var/log/inject/littlewoods_uk.log &
/opt/home/merit/inject.py loft-us		 600 2>&1 >/var/log/inject/loft_us.log &
/opt/home/merit/inject.py macys-us		 600 2>&1 >/var/log/inject/macys_us.log &
/opt/home/merit/inject.py matalan-uk		 600 2>&1 >/var/log/inject/matalan_uk.log &
/opt/home/merit/inject.py m\&s-uk		 600 2>&1 >/var/log/inject/m\&s_uk.log &
/opt/home/merit/inject.py neimanmarkus-us	 600 2>&1 >/var/log/inject/neimanmarkus-us.log &
/opt/home/merit/inject.py net-a-porter-uk	 600 2>&1 >/var/log/inject/net-a-porter_uk.log &
# /opt/home/merit/inject.py net-a-porter-us	 600 2>&1 >/var/log/inject/net-a-porter_us.log &
/opt/home/merit/inject.py newlook-uk		 600 2>&1 >/var/log/inject/newlook_uk.log &
#/opt/home/merit/inject.py next-uk		 600 2>&1 >/var/log/inject/next_uk.log &
/opt/home/merit/inject.py nordstrom-us		 600 2>&1 >/var/log/inject/nordstrom_us.log &
/opt/home/merit/inject.py oasis-uk		 600 2>&1 >/var/log/inject/oasis_uk.log &
/opt/home/merit/inject.py oldnavy-us		 600 2>&1 >/var/log/inject/oldnavy_us.log &
/opt/home/merit/inject.py peacocks-uk		 600 2>&1 >/var/log/inject/peacocks_uk.log &
#/opt/home/merit/inject.py piperlime-us		 600 2>&1 >/var/log/inject/piperlime_us.log &
/opt/home/merit/inject.py reiss-uk		 600 2>&1 >/var/log/inject/reiss_uk.log &
/opt/home/merit/inject.py riverisland-uk	 600 2>&1 >/var/log/inject/riverisland_uk.log &
/opt/home/merit/inject.py saks-us		 600 2>&1 >/var/log/inject/saks_us.log &
/opt/home/merit/inject.py sears-us		 600 2>&1 >/var/log/inject/sears_us.log &
#/opt/home/merit/inject.py selfridges-uk		 600 2>&1 >/var/log/inject/selfridges_uk.log &
/opt/home/merit/inject.py simplybe-uk		 600 2>&1 >/var/log/inject/simplybe_uk.log &
/opt/home/merit/inject.py stagestores-us	 600 2>&1 >/var/log/inject/stagestores_us.log &
/opt/home/merit/inject.py target-us		 600 2>&1 >/var/log/inject/target_us.log &
/opt/home/merit/inject.py tedbaker-uk		 600 2>&1 >/var/log/inject/tedbaker_uk.log &
/opt/home/merit/inject.py tesco-uk		 600 2>&1 >/var/log/inject/tesco_uk.log &
/opt/home/merit/inject.py thelimited-us		 600 2>&1 >/var/log/inject/thelimited_us.log &
/opt/home/merit/inject.py theiconic-au 		 600 2>&1 >/var/log/inject/theiconic_au.log &
/opt/home/merit/inject.py topshop-uk		 600 2>&1 >/var/log/inject/topshop_uk.log &
# /opt/home/merit/inject.py topshop-us		 600 2>&1 >/var/log/inject/topshop_us.log &
/opt/home/merit/inject.py uniqlo-uk		  600 2>&1 >/var/log/inject/uniqlo_uk.log &
/opt/home/merit/inject.py urbanoutfitters-us	 600 2>&1 >/var/log/inject/urbanoutfitters_us.log &
/opt/home/merit/inject.py walmart-us		 600 2>&1 >/var/log/inject/walmart_us.log &
/opt/home/merit/inject.py zalando-uk		 600 2>&1 >/var/log/inject/zalando_uk.log &
/opt/home/merit/inject.py zappos-us		 600 2>&1 >/var/log/inject/zappos_us.log &
#/opt/home/merit/inject.py zara-uk		 600 2>&1 >/var/log/inject/zara_uk.log &
# /opt/home/merit/inject.py zara-us		 600 2>&1 >/var/log/inject/zara_us.log &
