#!/bin/bash

/opt/home/merit/report.py abercrombie-us
/opt/home/merit/report.py americaneagle-us
/opt/home/merit/report.py anntaylor-us
/opt/home/merit/report.py anthropologie-us
/opt/home/merit/report.py asda_george-uk
/opt/home/merit/report.py asos-uk
/opt/home/merit/report.py asos-us
/opt/home/merit/report.py bananarepublic-us
/opt/home/merit/report.py bealls-us
/opt/home/merit/report.py bhs-uk
/opt/home/merit/report.py bloomingdales-us
/opt/home/merit/report.py chicos-us
/opt/home/merit/report.py coaststores-uk
/opt/home/merit/report.py debenhams-uk
/opt/home/merit/report.py dorothy_perkins-uk
/opt/home/merit/report.py evans-uk
/opt/home/merit/report.py express-us
/opt/home/merit/report.py forever21-us
/opt/home/merit/report.py gap-uk
/opt/home/merit/report.py gap-us
/opt/home/merit/report.py h\&m-uk
/opt/home/merit/report.py hollister-us
/opt/home/merit/report.py houseoffraser-uk
/opt/home/merit/report.py jcpenney-us
/opt/home/merit/report.py jcrew-us
/opt/home/merit/report.py jigsaw-uk
/opt/home/merit/report.py johnlewis-uk
/opt/home/merit/report.py kmart-us
/opt/home/merit/report.py kohls-us
/opt/home/merit/report.py landsend-us
/opt/home/merit/report.py littlewoods-uk
/opt/home/merit/report.py loft-us
/opt/home/merit/report.py macys-us
/opt/home/merit/report.py matalan-uk
/opt/home/merit/report.py m\&s-uk
/opt/home/merit/report.py neimanmarkus-us
/opt/home/merit/report.py net-a-porter-uk
/opt/home/merit/report.py net-a-porter-us
/opt/home/merit/report.py newlook-uk
/opt/home/merit/report.py next-uk
/opt/home/merit/report.py oasis-uk
/opt/home/merit/report.py oldnavy-us
/opt/home/merit/report.py peacocks-uk
/opt/home/merit/report.py piperlime-us
/opt/home/merit/report.py reiss-uk
/opt/home/merit/report.py riverisland-uk
/opt/home/merit/report.py saks-us
/opt/home/merit/report.py sears-us
/opt/home/merit/report.py selfridges-uk
/opt/home/merit/report.py simplybe-uk
/opt/home/merit/report.py stagestores-us
/opt/home/merit/report.py target-us
/opt/home/merit/report.py tedbaker-uk
/opt/home/merit/report.py tesco-uk
/opt/home/merit/report.py thelimited-us
/opt/home/merit/report.py topshop-uk
/opt/home/merit/report.py topshop-us
/opt/home/merit/report.py uniqlo-uk
/opt/home/merit/report.py urbanoutfitters-us
/opt/home/merit/report.py walmart-us
/opt/home/merit/report.py zalando-uk
/opt/home/merit/report.py zappos-us
/opt/home/merit/report.py zara-uk
